### ISSUE TITLE
Web Technologies Detector for a particular website.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#302]
hint: use python-Wappalyzer

**Comment by HaripriyaB** [comment]
I would like to work on this issue. (Python)

**Comment by Ninjavin** [comment]
@tejan-singh @yashaswibiyahut Can I work on it in NodeJS?

**Comment by tejan-singh** [comment]
@Ninjavin can you work on this in javascript?

**Comment by Ninjavin** [comment]
@tejan-singh I was going to use https://www.npmjs.com/package/wappalyzer . Do you not want me to use this?

**Comment by tejan-singh** [comment]
@Ninjavin okey you can work in NodeJS

**Comment by Ninjavin** [comment]
@tejan-singh Can I ask why are you removing the Medium Level or Hard label tags and suddenly relabelling the issue Easy? You did the same for PDF Merger too. (If you do not want us to use libraries you can mention that but this relabelling is creating a lot of trouble)

**Comment by tejan-singh** [comment]
@Ninjavin Actually, when we label an issue as a medium, we expect participants to submit issues with at least 50 lines of code. If someone presents code with less than that, it would not be very pleasant for them to ask to write the whole code again after spending so much time. So, I accept solutions without asking to code also at an easy level. 

If you feel it's confusing you at any level, you can ask us anytime for clarification. We will provide you with clarification. We all are here to help you, okay. 

I change labels when I feel participants are not able to find solutions at that level.

**Comment by Ninjavin** [comment]
@tejan-singh Thank you for being so polite and answering to my question.

However, when you are considering the number of lines of code, you are actually ignoring the amount of research done to write that code. If you consider languages like C, C++ or Java they have usually larger number of lines than Python and JS (as well as, NodeJS) for obvious reasons.

So I guess you should create different issues for different languages and label them accordingly. 

Also, as an engineering student and a developer I have always been guided by my mentors to write shorter and efficient code.
The message you are putting across to developers like me is to write as large a code as possible for our PRs, no matter the efficiency.

I don’t want this to come off the wrong way but if you choose to persist with this convention, I will maximize the number of lines in my code henceforth, since these issues will otherwise be labelled Easy.

**Comment by tejan-singh** [comment]
@Ninjavin thanks for suggestions. I will consider all these things for our future work.
